# Generated by Django 3.1.7 on 2021-03-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='project-1', unique=True),
            preserve_default=False,
        ),
    ]
