# Generated by Django 3.1.7 on 2021-03-11 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pentest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pentest',
            name='attr',
            field=models.CharField(choices=[('Fuzzing', (('url', 'URL'), ('port', 'PORT'))), ('Brute Force', (('url', 'URL'), ('filename', 'File Name')))], max_length=50),
        ),
        migrations.AlterField(
            model_name='pentest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='app.project'),
        ),
    ]
